version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        container_name: vtuber-collection
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    webserver:
        image: nginx:latest
        container_name: nginx-webserver-vtuber
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: mysql-database-vtuber
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        profiles:
            - dev
        networks:
            - app-network

networks:
    app-network:
